apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-xhms
  namespace: nmukherj-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:ea6420c7372e06c72d55ee78b74830447c6b1ff6cc7c34b5aa1a2cd8302ca340
        name: my-nodejs
        resources: {}
status: {}
